[Update] scripts

diff --git a/bin/git-workbranch b/bin/git-workbranch
--- a/bin/git-workbranch
+++ b/bin/git-workbranch
@@ -186,6 +186,11 @@ function git-workbranch-status {
 	done
 }
 
+function git-workbranch-origin {
+	git worktree list | grep  "\[$(git-workbranch-parent)\]" | cut -d -f1
+}
+
+
 function git-workbranch-prune {
 	local parent=$(git-workbranch-parent)
 	local parent_path="$(git-workbranch-util branch-path $parent)"
@@ -207,54 +212,54 @@ function git-workbranch-prune {
 	git -C "$parent_path" worktree prune
 }
 
-# -- doc
-# Removes the current branch, making sure it is pushed
-function git-workbranch-remove {
-	local BRANCH=""
-	local MATCHING_BRANCH=""
-	if [ -v 1 ]; then
-		BRANCH="$1"
-	else
-		BRANCH="$(git branch --show-current)"
-	fi
-	if ! MATCHING_BRANCH="$(git-pick-branch "$BRANCH")"; then
-		echo "$MATCHING_BRANCH"
-		exit 1
-	fi
-	# 	git-workbranch-util err "Cannot remove brnach as it has changed
-	local branch_path="$(git-workbranch-util branch-path)"
-	if [ -n "$(git-workbranch-util has-changes "$branch_path")" ]; then
-		git-workbranch-util err "Cannot remove branch, as it has uncommited local changes"
-		git status --porcelain
-		git-workbranch-util tip "Run 'git commit -a' to commit outstanding changes"
-		exit 1
-	fi
-	local root_path="$(git-workbranch-util branch-path $(git-workbranch-parent))"
-	if [ "$branch_path" = "$root_path" ]; then
-		git-workbranch-util err "Cannot remove the parent branch: $branch_path"
-		exit 1
-	fi
-	local cur_dir="$(pwd)"
-	cd "$branch_path"
-	local should_push="$(git-workbranch-util should-push)"
-	cd "$cur_dir"
-	if [ -n "$should_push" ]; then
-		git-workbranch-util log "Cannot remove branch, as it has outstanding changes to publish"
-		echo "$should_push"
-		git-workbranch-util tip "Run 'git push' and make sure local and remote are up-to-date and in sync"
-		exit 1
-	fi
-	if [ "$cur_dir" = "$branch_path" ]; then
-		git-workbranch-util log "Moving to parent branch path: $root_path"
-		cd "$root_path"
-	fi
-	local branch_basename="$(basename $branch_path)"
-	local archive_name="$branch_basename.$(date +"%Y%m%dT%H%M%S%3N").tar.gz"
-	env -C "$(dirname $branch_path)" tar cfz "$archive_name" "$branch_basename"
-	git worktree remove "$branch_path"
-	git-workbranch-util log "Created archive at: $archive_name"
-
-}
+# # -- doc
+# # Removes the current branch, making sure it is pushed
+# function git-workbranch-remove {
+# 	local BRANCH=""
+# 	local MATCHING_BRANCH=""
+# 	if [ -v 1 ]; then
+# 		BRANCH="$1"
+# 	else
+# 		BRANCH="$(git branch --show-current)"
+# 	fi
+# 	if ! MATCHING_BRANCH="$(git-pick-branch "$BRANCH")"; then
+# 		echo "$MATCHING_BRANCH"
+# 		exit 1
+# 	fi
+# 	# 	git-workbranch-util err "Cjjnnot remove brnach as it has changed
+# 	local branch_path="$(git-workbranch-util branch-path)"
+# 	if [ -n "$(git-workbranch-util has-changes "$branch_path")" ]; then
+# 		git-workbranch-util err "Cannot remove branch, as it has uncommited local changes"
+# 		git status --porcelain
+# 		git-workbranch-util tip "Run 'git commit -a' to commit outstanding changes"
+# 		exit 1
+# 	fi
+# 	local root_path="$(git-workbranch-util branch-path $(git-workbranch-parent))"
+# 	if [ "$branch_path" = "$root_path" ]; then
+# 		git-workbranch-util err "Cannot remove the parent branch: $branch_path"
+# 		exit 1
+# 	fi
+# 	local cur_dir="$(pwd)"
+# 	cd "$branch_path"
+# 	local should_push="$(git-workbranch-util should-push)"
+# 	cd "$cur_dir"
+# 	if [ -n "$should_push" ]; then
+# 		git-workbranch-util log "Cannot remove branch, as it has outstanding changes to publish"
+# 		echo "$should_push"
+# 		git-workbranch-util tip "Run 'git push' and make sure local and remote are up-to-date and in sync"
+# 		exit 1
+# 	fi
+# 	if [ "$cur_dir" = "$branch_path" ]; then
+# 		git-workbranch-util log "Moving to parent branch path: $root_path"
+# 		cd "$root_path"
+# 	fi
+# 	local branch_basename="$(basename $branch_path)"
+# 	local archive_name="$branch_basename.$(date +"%Y%m%dT%H%M%S%3N").tar.gz"
+# 	env -C "$(dirname $branch_path)" tar cfz "$archive_name" "$branch_basename"
+# 	git worktree remove "$branch_path"
+# 	git-workbranch-util log "Created archive at: $archive_name"
+# 
+# }
 
 #
 # TODO: Should merge --squash back to main
@@ -276,14 +281,73 @@ function git-workbranch-merge {
 
 # -- doc
 # Closes the current branch
-function git-workbranch-close {
-	local parent="$(git-workbranch-parent)"
-	local current="$(git-workbranch-current)"
+# function git-workbranch-close {
+# 	local parent="$(git-workbranch-parent)"
+# 	local current="$(git-workbranch-current)"
+# 	if [ -n "$(git-workbranch-util has-changes)" ]; then
+# 		git-workbranch-util err "Current branch has changes"
+# 		git status --porcelain
+# 		git-workbranch-util tip "Run 'git commit -a' to commit outstanding changes"
+# 		exit 1
+# 	fi
+# 	if [ -z "$parent" ]; then
+# 		git-workbranch-util err "Can't find a parent branch"
+# 		exit 1
+# 	fi
+# 	if [ -z "$current" ]; then
+# 		git-workbranch-util err "Can't find a current branch"
+# 		exit 1
+# 	fi
+# 	if [ -z "$(git-workbranch-util is-merged)" ]; then
+# 		git-workbranch-util err "Current branch is not merged in parent"
+# 		git-workbranch-util tip "Here is the list of differences between $current and $parent"
+# 		local to_pull="$(GIT_PAGER= git log "$current..$parent" --pretty=format:'%ad %h %d %s' --date=iso)"
+# 		local to_push="$(GIT_PAGER= git log "$parent..$current" --pretty=format:'%ad %h %d %s' --date=iso)"
+# 		if [ -n "$to_push" ]; then
+# 			git-workbranch-util log "Here are changes that need to be pushed to $parent"
+# 			git-workbranch-util pre "$to_push"
+# 			local parent_path="$(git worktree list | grep -F "[$parent]" | cut -d' ' -f1)"
+# 			git-workbranch-util tip "run 'git -C $parent_path merge --squash $current'"
+# 		fi
+# 		if [ -n "$to_pull" ]; then
+# 			git-workbranch-util log "Here are changes that need to be merged from $parent"
+# 			git-workbranch-util pre "$to_pull"
+# 			git-workbranch-util tip "run 'git rebase $parent' or 'git merge --squash $parent'"
+# 		fi
+# 		local parent="$(git-workbranch-parent)"
+# 		exit 1
+# 	fi
+# 	# git-workbranch-merge
+# 	# TODO: If things succeed, then we can safely remove that branch
+# 	git-workbranch-util log "Workbranch $current was merged with $parent, closing…"
+# 	git tag "archive/$current"
+# 	git branch --delete --force "$current"
+# }
+
+
+# -- doc
+# Creates an archive of the current branch
+function git-workbranch-archive {
+	local has_force=0
+	if [ ! -z "$@" ]; then
+		case "$1" in
+			-f|--force)
+				shift
+				has_force=1
+				;;
+		esac
+	fi
 	if [ -n "$(git-workbranch-util has-changes)" ]; then
-		git-workbranch-util err "Current branch has changes"
-		git status --porcelain
-		git-workbranch-util tip "Run 'git commit -a' to commit outstanding changes"
-		exit 1
+		if [ $has_force == 0 ]; then
+			git-workbranch-util err "Current branch has changes"
+			git-workbranch-util list-changes
+			git-workbranch-util tip "Run 'git commit -a' to commit outstanding changes"
+			git-workbranch-util tip "Or add '-f' '--force' to proceed"
+			exit 1
+		else
+			git-workbranch-util log "Workbranch has uncommitted changes"
+			git-workbranch-util list-changes
+		fi
 	fi
 	if [ -z "$parent" ]; then
 		git-workbranch-util err "Can't find a parent branch"
@@ -293,37 +357,31 @@ function git-workbranch-close {
 		git-workbranch-util err "Can't find a current branch"
 		exit 1
 	fi
-	if [ -z "$(git-workbranch-util is-merged)" ]; then
-		git-workbranch-util err "Current branch is not merged in parent"
-		git-workbranch-util tip "Here is the list of differences between $current and $parent"
-		local to_pull="$(GIT_PAGER= git log "$current..$parent" --pretty=format:'%ad %h %d %s' --date=iso)"
-		local to_push="$(GIT_PAGER= git log "$parent..$current" --pretty=format:'%ad %h %d %s' --date=iso)"
-		if [ -n "$to_push" ]; then
-			git-workbranch-util log "Here are changes that need to be pushed to $parent"
-			git-workbranch-util pre "$to_push"
-			local parent_path="$(git worktree list | grep -F "[$parent]" | cut -d' ' -f1)"
-			git-workbranch-util tip "run 'git -C $parent_path merge --squash $current'"
-		fi
-		if [ -n "$to_pull" ]; then
-			git-workbranch-util log "Here are changes that need to be merged from $parent"
-			git-workbranch-util pre "$to_pull"
-			git-workbranch-util tip "run 'git rebase $parent' or 'git merge --squash $parent'"
-		fi
-		local parent="$(git-workbranch-parent)"
-		exit 1
-	fi
-	# git-workbranch-merge
-	# TODO: If things succeed, then we can safely remove that branch
-	git-workbranch-util log "Workbranch $current was merged with $parent, closing…"
-	git tag "archive/$current"
-	git branch --delete --force "$current"
-}
 
+}
 function git-workbranch-util {
 	local parent
 	local path
 	local current
+	local item
+	local subitem
 	case $1 in
+	archive)
+		shift
+		local branch_path="$(git-workbranch-util branch-path)"
+		local branch_basename="$(basename $branch_path)"
+		local archive_name="$branch_basename.$(date +"%Y%m%dT%H%M%S%3N").tar.bz2"
+		local excludes="$(mktemp git-workbranch-excludes-XXXX.lst)"
+		echo "$excludes"
+		touch "$excludes"
+		for item in .gitgnore "$HOME/.gitignore"; do
+			if [ -e "$item" ]; then cat $item >> "$excludes"; fi
+		done
+		# FIXME: That doesn't work, that still takes a complete archive
+		env -C "$(dirname $branch_path)" tar --exclude-from="$(realpath "$excludes")" -cJvf "$archive_name" "$branch_basename"
+		unlink $excludes
+		echo $(realpath $(dirname $branch_path)/$archive_name)
+	;;
 	branch-path)
 		shift
 		if [ -v 1 ]; then current="$1"; else current="$(git-workbranch-current)"; fi
@@ -350,6 +408,18 @@ function git-workbranch-util {
 			echo -n "1"
 		fi
 		;;
+	list-changes)
+		shift
+		for item in $(git status --porcelain | cut -c 3-); do
+			if [ -e "$item/.git" ]; then
+				for subitem in $(git -C "$item" status --porcelain | cut -c 3-); do
+					echo -e "$BOLD"$item"$RESET"/$subitem
+				done
+			else
+				echo "$item"
+			fi
+		done
+		;;	
 	has-incoming)
 		shift
 		if [ -v 1 ]; then parent="$1"; else parent="$(git-workbranch-parent)"; fi
@@ -424,11 +494,6 @@ me | merge)
 	shift
 	git-workbranch-merge "$@"
 	;;
-
-cl | close)
-	shift
-	git-workbranch-close "$@"
-	;;
 cu | current)
 	shift
 	git-workbranch-current "$@"
@@ -437,10 +502,20 @@ pa | parent)
 	shift
 	git-workbranch-parent "$@"
 	;;
-rm | remove)
+ar | archive)
 	shift
-	git-workbranch-remove "$@"
+	git-workbranch-archive "$@"
 	;;
+# NOTE: These are not working
+# cl | close)
+# 	shift
+# 	git-workbranch-close "$@"
+# 	;;
+# 
+# rm | remove)
+# 	shift
+# 	git-workbranch-remove "$@"
+# 	;;
 ls | list)
 	shift
 	git-workbranch-list "$@"
@@ -453,16 +528,25 @@ pr | prune)
 	shift
 	git-workbranch-prune "$@"
 	;;
+or | origin)
+	shift
+	git-workbranch-origin "$@"
+	;;
+do | util)
+	shift
+	git-workbranch-util "$@"
+	;;
+
 *)
 	echo "git-workbranch available commands:"
 	echo " - create   BRANCH_NAME:   Creates a new branch worktree"
 	echo " - checkout BRANCH_NAME:   Checks out a new branch worktree"
 	echo " - merge    [BRANCH_NAME]"
 	echo " - close    [BRANCH_NAME]"
-	echo " - remove   [BRANCH_NAME]"
-	echo " - prune"
+	echo " - archive                 Archives the current branch as a tar.bz2"
 	echo " - current                 Returns the name of the current branch"
 	echo " - parent                  Returns the name of the parent branch"
+	echo " - origin                  Returns the path to the origin repository"
 	echo " - list:                   List the checked out worktree branches"
 	echo " - status:                 Lists the status of each worktree branch"
 	;;
