[Update] git-workbranch: implemented close

diff --git a/bin/git-workbranch b/bin/git-workbranch
--- a/bin/git-workbranch
+++ b/bin/git-workbranch
@@ -6,7 +6,9 @@ if [ ! -v NO_COLOR ]; then
 	GREEN='\033[0;32m'
 	BLUE='\033[0;34m'
 	ORANGE='\033[0;33m'
+	YELLOW='\033[1;33m'
 	CYAN='\033[0;36m'
+	PURPLE='\033[0;35m'
 	GREY='\033[0;37m'
 	LIGHT_GREY='\033[0;97m'
 	RESET='\033[0m'
@@ -102,13 +104,13 @@ function git-workbranch-checkout {
 		exit 1
 	fi
 	local BRANCH_PATH="$(git rev-parse --show-toplevel)/../$REPO_NAME--$MATCHING_BRANCH"
-	echo "--- Selected branch: $MATCHING_BRANCH at '$(realpath --relative-to="$PWD" $BRANCH_PATH)'"
+	git-workbranch-util log "Selected branch: $MATCHING_BRANCH at '$(realpath --relative-to="$PWD" $BRANCH_PATH)'"
 	if [ -e "$BRANCH_PATH" ]; then
-		echo "--- Worktree already exists: $(realpath --relative-to="$PWD" $BRANCH_PATH)"
+		git-workbranch-util log "Worktree already exists: $(realpath --relative-to="$PWD" $BRANCH_PATH)"
 	else
 		git worktree add "$BRANCH_PATH" "$MATCHING_BRANCH"
 		git -C "$BRANCH_PATH" branch --set-upstream-to=origin/$MATCHING_BRANCH $MATCHING_BRANCH
-		echo "--- Worktree created at: $(realpath --relative-to="$PWD" $BRANCH_PATH)"
+		git-workbranch-util log "Worktree created at: $(realpath --relative-to="$PWD" $BRANCH_PATH)"
 	fi
 }
 
@@ -119,11 +121,11 @@ function git-workbranch-list {
 	if [ -v 1 ]; then BRANCH="$1"; fi
 	local REPO_BRANCHES="$(git branch -a | grep -v 'HEAD' | sed 's|remotes/origin/||g;s|[+* ]||g' | sort | uniq)"
 	local REPO_NAME="$(basename $(git rev-parse --show-toplevel) | sed 's|--.*||g')"
-	local branch
-	local branch_path
+	local branch=""
+	local branch_path=""
 	local base_path="$(git rev-parse --show-toplevel)/.."
-	local checked_branches
-	local unchecked_branches
+	local checked_branches=""
+	local unchecked_branches=""
 	for branch in $REPO_BRANCHES; do
 		branch_path="$base_path/$REPO_NAME--$branch"
 		if [ -e "$branch_path" ]; then
@@ -172,30 +174,66 @@ function git-workbranch-status {
 			local archived="$(git tag --points-at | grep archive/$branch | cut -d/ -f2)"
 			local status=
 			if [ -n "$archived" ]; then
-				archived=" $GREEN$BOLD archived$RESET"
+				archived=" $PURPLE$BOLD archived$RESET"
 			fi
 			if [ "$incoming" != "0" ]; then incoming="←$incoming"; else incoming="●"; fi
 			if [ "$outgoing" != "0" ]; then outgoing="→$outgoing"; else outgoing="●"; fi
 			if [ "$incoming" = "$outgoing" ] && [ "$incoming" = "●" ]; then
-				status=" $GREEN$BOLD✓ synced$RESET"
+				status="$GREEN$BOLD synced ✓$RESET"
 			fi
-			echo -e "$BOLD$(basename $branch_path)$RESET $GREEN$incoming $BLUE$outgoing$RESET$status$archived"
+			echo -e "$BOLD$(basename $branch_path)$RESET $GREEN$incoming $BLUE$outgoing$RESET$archived$status"
 			cd "$cwd"
 		fi
 	done
 }
 
+# -- doc
+# Removes the current branch, making sure it is pushed
 function git-workbranch-remove {
-	local BRANCH="$1"
-	local MATCHING_BRANCH
-	if [ -z "$1" ]; then
+	local BRANCH=""
+	local MATCHING_BRANCH=""
+	if [ -v 1 ]; then
+		BRANCH="$1"
+	else
 		BRANCH="$(git branch --show-current)"
 	fi
 	if ! MATCHING_BRANCH="$(git-pick-branch "$BRANCH")"; then
 		echo "$MATCHING_BRANCH"
 		exit 1
 	fi
-	git worktree remove "$MATCHING_BRANCH"
+	# 	git-workbranch-util err "Cannot remove brnach as it has changed
+	local branch_path="$(git-workbranch-util branch-path)"
+	if [ -n "$(git-workbranch-util has-changes "$branch_path")" ]; then
+		git-workbranch-util err "Cannot remove branch, as it has uncommited local changes"
+		git status --porcelain
+		git-workbranch-util tip "Run 'git commit -a' to commit outstanding changes"
+		exit 1
+	fi
+	local root_path="$(git-workbranch-util branch-path $(git-workbranch-parent))"
+	if [ "$branch_path" = "$root_path" ]; then
+		git-workbranch-util err "Cannot remove the parent branch: $branch_path"
+		exit 1
+	fi
+	local cur_dir="$(pwd)"
+	cd "$branch_path"
+	local should_push="$(git-workbranch-util should-push)"
+	cd "$cur_dir"
+	if [ -n "$should_push" ]; then
+		git-workbranch-util log "Cannot remove branch, as it has outstanding changes to publish"
+		echo "$should_push"
+		git-workbranch-util tip "Run 'git push' and make sure local and remote are up-to-date and in sync"
+		exit 1
+	fi
+	if [ "$cur_dir" = "$branch_path" ]; then
+		git-workbranch-util log "Moving to parent branch path: $root_path"
+		cd "$root_path"
+	fi
+	local branch_basename="$(basename $branch_path)"
+	local archive_name="$branch_basename.$(date +"%Y%m%dT%H%M%S%3N").tar.gz"
+	env -C "$(dirname $branch_path)" tar cfz "$archive_name" "$branch_basename"
+	git worktree remove "$branch_path"
+	git-workbranch-util log "Created archive at: $archive_name"
+
 }
 
 #
@@ -263,10 +301,32 @@ function git-workbranch-close {
 
 function git-workbranch-util {
 	local parent
+	local path
 	local current
 	case $1 in
+	branch-path)
+		shift
+		if [ -v 1 ]; then current="$1"; else current="$(git-workbranch-current)"; fi
+		git worktree list | grep -F "[$current]" | cut -d' ' -f1
+		;;
+	branch-current)
+		shift
+		git rev-parse --abbrev-ref HEAD
+		;;
+	branch-origin)
+		shift
+		git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null
+		;;
+	should-push)
+		current="$(git-workbranch-util branch-origin)"
+		parent="$(git-workbranch-util branch-current)"
+		GIT_PAGER= git log "$current..$parent" --pretty=format:'%ad %h %d %s' --date=iso
+		shift
+		;;
 	has-changes)
-		if git status --porcelain | grep 'M '; then
+		shift
+		if [ -v 1 ]; then path="$1"; else path="."; fi
+		if git -C "$path" status --porcelain | grep 'M '; then
 			echo -n "1"
 		fi
 		;;
@@ -371,8 +431,9 @@ st | status)
 	echo "git-workbranch available commands:"
 	echo " - create   BRANCH_NAME:   Creates a new branch worktree"
 	echo " - checkout BRANCH_NAME:   Checks out a new branch worktree"
-	echo " - close    [BRANCH_NAME]: Closed the branch branch worktress and removes it"
-	echo " - remove   [BRANCH_NAME]: Remove the current or given/current branch from the worktree"
+	echo " - merge    [BRANCH_NAME]"
+	echo " - close    [BRANCH_NAME]"
+	echo " - remove   [BRANCH_NAME]"
 	echo " - current                 Returns the name of the current branch"
 	echo " - parent                  Returns the name of the parent branch"
 	echo " - list:                   List the checked out worktree branches"
